# Properties for a Managed Environment go here.
spring:
  application:
    name: Communications

queue:
  priority:
    high: 0 * * ? * *
    medium: 0 0 * ? * *
    low: 0 0 */3 ? * *

mongock:
  change-logs-scan-package: health.safe.api.opencdx.communications.changelog