# Properties for a Managed Environment go here.
spring:
  application:
    name: Communications
grpc:
  port: 9390

server:
  port: 8380

queue:
  priority:
    high: 0 * * ? * *
    medium: 0 0 * ? * *
    low: 0 0 */3 ? * *

mongock:
  change-logs-scan-package: cdx.opencdx.communications.changelog