# Properties for NATS go here.

# See https://github.com/nats-io/spring-nats/blob/main/nats-spring/src/main/java/io/nats/spring/boot/autoconfigure/NatsConnectionProperties.java
nats:
  spring:
    server: nats://nats:4222
    keyStorePath: /certs/opencdx-keystore.p12
    keyStorePassword: opencdx
    keyStoreType: PKCS12
    trustStorePath: /certs/opencdx-keystore.p12
    trustStorePassword: opencdx
    trustStoreType: PKCS12
