spring:
  application:
    name: Gateway
  ssl:
    bundle:
      jks:
        web-server:
          key:
            alias: ${spring.application.name}
          keystore:
            location: file:/certs/opencdx-keystore.p12
            password: opencdx
            type: PKCS12
  cloud:
    gateway:
      httpclient:
        ssl:
          useInsecureTrustManager: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      enabled: true
      routes:
        - id: grpc-helloworld
          uri: lb:https://helloworld:9790
          predicates:
            - Path=/grpc-helloworld/**
          filters:
            - AddResponseHeader=X-Request-header, header-value
        - id: grpc-audit
          uri: lb:https://audit:9290
          predicates:
            - Path=/grpc-audit/**
          filters:
            - AddResponseHeader=X-Request-header, header-value
        - id: grpc-communications
          uri: lb:https://communications:9390
          predicates:
            - Path=/grpc-communications/**
          filters:
            - AddResponseHeader=X-Request-header, header-value
        - id: grpc-connected-test
          uri: lb:https://connected-test:9590
          predicates:
            - Path=/grpc-connected-test/**
          filters:
            - AddResponseHeader=X-Request-header, header-value
        - id: grpc-media
          uri: lb:https://media:9490
          predicates:
            - Path=/grpc-media/**
          filters:
            - AddResponseHeader=X-Request-header, header-value
eureka:
  client:
    service-url:
      defaultZone: http://admin:8761/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    nonSecurePortEnabled: false
    securePortEnabled: true
    statusPageUrl: https://${spring.application.name}:${server.port}/info
    healthCheckUrl: https://${spring.application.name}:${server.port}/actuator/health
    homePageUrl: https://${spring.application.name}:${server.port}/

management:
  endpoint:
    gateway:
      enabled: true
    health:
      probes:
        enabled: true
      enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8880
  ssl:
    enabled: true
    key-alias: ${spring.application.name}
    key-store-password: opencdx
    key-store: file:/certs/opencdx-keystore.p12
    key-store-type: PKCS12
  http2:
    enabled: true