spring:
  cloud:
    gateway:
      httpclient:
        ssl:
          useInsecureTrustManager: true
  application:
    name: Gateway
  ssl:
    bundle:
      jks:
        web-server:
          key:
            alias: ${spring.application.name}
          keystore:
            location: file:/certs/opencdx-keystore.p12
            password: opencdx
            keystore.type: PKCS12
eureka:
  client:
    service-url:
      defaultZone: http://admin:8761/eureka/
  instance:
    nonSecurePortEnabled: false
    securePortEnabled: true
    statusPageUrl: https://${spring.application.name}:${server.port}/info
    healthCheckUrl: https://${spring.application.name}:${server.port}/actuator/health
    homePageUrl: https://${spring.application.name}:${server.port}/

management:
  endpoint:
    health:
      probes:
        enabled: true
      enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8880
  ssl:
    enabled: true
    key-alias: ${spring.application.name}
    key-store-password: opencdx
    key-store: file:/certs/opencdx-keystore.p12
    key-store-type: PKCS12
    trust-store: file:/certs/opencdx-keystore.p12
    trust-store-password: opencdx
    trust-store-type: PKCS12
  http2:
    enabled: true