spring:
  application:
    name: Gateway
  ssl:
    bundle:
      jks:
        web-server:
          key:
            alias: ${spring.application.name}
          keystore:
            location: file:/certs/opencdx-keystore.p12
            password: opencdx
            keystore.type: PKCS12
eureka:
  client:
    service-url:
      defaultZone: http://admin:8761/eureka/
  instance:
    nonSecurePortEnabled: false
    securePortEnabled: true
    statusPageUrl: https://${spring.application.name}:${server.port}/info
    healthCheckUrl: https://${spring.application.name}:${server.port}/actuator/health
    homePageUrl: https://${spring.application.name}:${server.port}/

management:
  endpoint:
    health:
      probes:
        enabled: true
      enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8880
  ssl:
    enabled: true
    bundle: web-server
    client-auth: none
  http2:
    enabled: true