spring:
  application:
    name: Gateway
  ssl:
    bundle:
      jks:
        web-server:
          key:
            alias: gateway
          keystore:
            location: file:/certs/opencdx-keystore.p12
            password: opencdx
            type: PKCS12
  cloud:
    gateway:
      httpclient:
        ssl:
          useInsecureTrustManager: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      enabled: true
      routes:
        - id: dashboard
          uri: http://dashboard:3005
          predicates:
            - Path=/dashboard/**
          filters:
            - RewritePath=/dashboard/(?<segment>.*), /$\{segment}
        - id: grpc-helloworld
          uri: https://helloworld:9090
          predicates:
            - Path=/cdx.opencdx.grpc.helloworld.Greeter/**
          filters:
            - AddResponseHeader=X-Request-header, header-value
        - id: grpc-audit
          uri: https://audit:9090
          predicates:
            - Path=/cdx.opencdx.grpc.audit.AuditService/**
          filters:
            - AddResponseHeader=X-Request-header, header-value
        - id: grpc-protector
          uri: https://protector:9090
          predicates:
            - Path=/cdx.opencdx.grpc.protector.NeuralProtectorService/**
          filters:
            - AddResponseHeader=X-Request-header, header-value            
        - id: grpc-predictor
          uri: https://predictor:9090
          predicates:
            - Path=/cdx.opencdx.grpc.predictor.NeuralPredictorService/**
          filters:
            - AddResponseHeader=X-Request-header, header-value  
        - id: grpc-questionnaire
          uri: https://questionnaire:9090
          predicates:
            - Path=/cdx.opencdx.grpc.questionnaire.QuestionnaireService/**
          filters:
            - AddResponseHeader=X-Request-header, header-value  
        - id: grpc-communications
          uri: https://communications:9090
          predicates:
            - Path=/cdx.opencdx.grpc.communication.CommunicationService/**
          filters:
            - AddResponseHeader=X-Request-header, header-value
        - id: grpc-connected-test
          uri: https://connected-test:9090
          predicates:
            - Path=/cdx.opencdx.grpc.connected.HealthcareService/**
          filters:
            - AddResponseHeader=X-Request-header, header-value
        - id: grpc-media
          uri: https://media:9090
          predicates:
            - Path=/cdx.opencdx.grpc.media.MediaService/**
          filters:
            - AddResponseHeader=X-Request-header, header-value
        - id: grpc-routine
          uri: https://routine:9090
          predicates:
            - Path=/cdx.opencdx.grpc.routine.RoutineSystemService/**
          filters:
            - AddResponseHeader=X-Request-header, header-value            
        - id: grpc-iam
          uri: https://iam:9090
          predicates:
            - Path=/cdx.opencdx.grpc.iam.IamUserService/**
          filters:
            - AddResponseHeader=X-Request-header, header-value
        - id: grpc-connected-test-country
          uri: https://connected-test:9090
          predicates:
            - Path=/cdx.opencdx.grpc.inventory.CountryService/**
          filters:
            - AddResponseHeader=X-Request-header, header-value
        - id: grpc-connected-test-device
          uri: https://connected-test:9090
          predicates:
            - Path=/cdx.opencdx.grpc.inventory.DeviceService/**
          filters:
            - AddResponseHeader=X-Request-header, header-value
        - id: grpc-connected-test-manufacturer
          uri: https://connected-test:9090
          predicates:
            - Path=/cdx.opencdx.grpc.inventory.ManufacturerService/**
          filters:
            - AddResponseHeader=X-Request-header, header-value
        - id: grpc-connected-test-testcase
          uri: https://connected-test:9090
          predicates:
            - Path=/cdx.opencdx.grpc.inventory.TestCaseService/**
          filters:
            - AddResponseHeader=X-Request-header, header-value
        - id: grpc-connected-test-vendor
          uri: https://connected-test:9090
          predicates:
            - Path=/cdx.opencdx.grpc.inventory.VendorService/**
          filters:
            - AddResponseHeader=X-Request-header, header-value
        - id: grpc-iam-profile
          uri: https://iam:9090
          predicates:
            - Path=/cdx.opencdx.grpc.profile.UserProfileService/**
          filters:
            - AddResponseHeader=X-Request-header, header-value
        - id: grpc-iam-workspace
          uri: https://iam:9090
          predicates:
            - Path=/cdx.opencdx.grpc.organization.WorkspaceService/**
          filters:
            - AddResponseHeader=X-Request-header, header-value
        - id: grpc-iam-organization
          uri: https://iam:9090
          predicates:
            - Path=/cdx.opencdx.grpc.organization.OrganizationService/**
          filters:
            - AddResponseHeader=X-Request-header, header-value
        - id: grpc-anf
          uri: https://anf:9090
          predicates:
            - Path=/cdx.opencdx.grpc.anf.ANFService/**
          filters:
            - AddResponseHeader=X-Request-header, header-value
        - id: grpc-predictor
          uri: https://predictor:9090
          predicates:
            - Path=/cdx.opencdx.grpc.neural.predictor.NeuralPredictorService/**
          filters:
            - AddResponseHeader=X-Request-header, header-value
        - id: grpc-protector
          uri: https://protector:9090
          predicates:
            - Path=/cdx.opencdx.grpc.neural.protector.NeuralProtectorService/**
          filters:
            - AddResponseHeader=X-Request-header, header-value
        - id: grpc-routine
          uri: https://routine:9090
          predicates:
            - Path=/cdx.opencdx.grpc.routine.RoutineSystemService/**
          filters:
            - AddResponseHeader=X-Request-header, header-value
eureka:
  client:
    service-url:
      defaultZone: https://discovery:8761/eureka/
    registry-fetch-interval-seconds: 5
    tls:
      enabled: 'true'
      key-store: file:/certs/opencdx-keystore.p12
      key-store-type: PKCS12
      key-store-password: opencdx
      trust-store: file:/certs/opencdx-keystore.p12
      trust-store-type: PKCS12
      trust-store-password: opencdx
      key-password: opencdx
  instance:
    nonSecurePortEnabled: false
    securePortEnabled: true
    statusPageUrl: https://${spring.application.name}:${server.port}/info
    healthCheckUrl: https://${spring.application.name}:${server.port}/actuator/health
    homePageUrl: https://${spring.application.name}:${server.port}/

management:
  endpoint:
    gateway:
      enabled: true
    health:
      probes:
        enabled: true
      enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    enabled: true
    sampling.probability: 1.0
    propagation:
      type: b3
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
logging.pattern.level: "trace_id=%mdc{traceId} span_id=%mdc{spanId} trace_flags=%mdc{traceFlags} %p"
server:
  port: 8080
  ssl:
    enabled: true
    bundle: web-server
    client-auth: none
  http2:
    enabled: true