# Properties for a Managed Environment go here.
spring:
  application:
    name: shipping
mongock:
  change-logs-scan-package: cdx.opencdx.shipping.changelog
  max-waiting-for-lock-minutes: 3
  lock-acquired-for-minutes: 2
  max-tries: 5
  service-identifier: ${spring.application.name}