version: '3'
services:
  helloworld:
    deploy:
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 5
        window: 60s
    image: opencdx/helloworld:latest
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
    depends_on:
      config:
        condition: service_healthy
      admin:
        condition: service_healthy
      database:
        condition: service_healthy
      nats:
        condition: service_started
    ports:
      - "8080:8080"
      - "9090:9090"
  communications:
    deploy:
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 5
        window: 60s
    image: opencdx/communications:latest
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
    depends_on:
      config:
        condition: service_healthy
      admin:
        condition: service_healthy
      database:
        condition: service_healthy
      nats:
        condition: service_started
    ports:
      - "8380:8380"
      - "9390:9390"
  audit:
    deploy:
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 5
        window: 60s
    image: opencdx/audit:latest
    healthcheck:
      test: "curl --fail --silent localhost:8280/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
    depends_on:
      config:
        condition: service_healthy
      admin:
        condition: service_healthy
      database:
        condition: service_healthy
      nats:
        condition: service_started

  tinkar:
    deploy:
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 5
        window: 60s
    image: opencdx/tinkar:latest
    healthcheck:
      test: "curl --fail --silent localhost:8180/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
    depends_on:
      config:
        condition: service_healthy
      admin:
        condition: service_healthy
      database:
        condition: service_healthy
    ports:
      - "8180:8180"
      - "9190:9190"

  admin:
    image: opencdx/admin:latest
    healthcheck:
      test: "curl --fail --silent localhost:8761/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5

    ports:
      - "8761:8761"

  config:
    image: opencdx/config:latest
    ports:
      - "8888:8888"
    depends_on:
      admin:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8888/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5

  database:
    image: postgres
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=opencdx
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
  nats:
    image: nats
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    environment:
      NATS_STREAM_MAX_AGE: 86400s