version: '3'
services:
  gateway:
    deploy:
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 5
        window: 60s
    image: opencdx/gateway:latest
    healthcheck:
      test: "curl -k --fail --silent https://localhost:8880/actuator/health | grep UP || exit 1"
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      config:
        condition: service_healthy
      admin:
        condition: service_healthy
      database:
        condition: service_healthy
      nats:
        condition: service_started
    volumes:
      - ../certs:/certs
    ports:
      - "8080:8080"
  helloworld:
    deploy:
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 5
        window: 60s
    image: opencdx/helloworld:latest
    healthcheck:
      test: "curl -k --fail --silent https://localhost:8080/actuator/health | grep UP || exit 1"
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      config:
        condition: service_healthy
      admin:
        condition: service_healthy
      database:
        condition: service_healthy
      nats:
        condition: service_started
    volumes:
      - ../certs:/certs

  iam:
    deploy:
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 5
        window: 60s
    image: opencdx/iam:latest
    healthcheck:
      test: "curl -k --fail --silent https://localhost:8680/actuator/health | grep UP || exit 1"
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      config:
        condition: service_healthy
      admin:
        condition: service_healthy
      database:
        condition: service_healthy
      nats:
        condition: service_started
    volumes:
      - ../certs:/certs

  media:
    deploy:
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 5
        window: 60s
    image: opencdx/media:latest
    healthcheck:
      test: "curl -k --fail --silent https://localhost:8480/actuator/health | grep UP || exit 1"
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      config:
        condition: service_healthy
      admin:
        condition: service_healthy
      database:
        condition: service_healthy
      nats:
        condition: service_started
    volumes:
      - ../certs:/certs

  connected-test:
    deploy:
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 5
        window: 60s
    image: opencdx/connected-test:latest
    healthcheck:
      test: "curl -k --fail --silent https://localhost:8580/actuator/health | grep UP || exit 1"
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      config:
        condition: service_healthy
      admin:
        condition: service_healthy
      database:
        condition: service_healthy
      nats:
        condition: service_started
    volumes:
      - ../certs:/certs

  communications:
    deploy:
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 5
        window: 60s
    image: opencdx/communications:latest
    healthcheck:
      test: "curl -k --fail --silent https://localhost:8380/actuator/health | grep UP || exit 1"
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    depends_on:
      config:
        condition: service_healthy
      admin:
        condition: service_healthy
      database:
        condition: service_healthy
      nats:
        condition: service_started
    volumes:
      - ../certs:/certs

  audit:
    deploy:
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 5
        window: 60s
    image: opencdx/audit:latest
    healthcheck:
      test: "curl -k --fail --silent https://localhost:8280/actuator/health | grep UP || exit 1"
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    depends_on:
      config:
        condition: service_healthy
      admin:
        condition: service_healthy
      database:
        condition: service_healthy
      nats:
        condition: service_started
    volumes:
      - ../certs:/certs

  tinkar:
    deploy:
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 5
        window: 60s
    image: opencdx/tinkar:latest
    healthcheck:
      test: "curl -k --fail --silent https://localhost:8180/actuator/health | grep UP || exit 1"
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    depends_on:
      config:
        condition: service_healthy
      admin:
        condition: service_healthy
      database:
        condition: service_healthy
      nats:
        condition: service_started
    volumes:
      - ../certs:/certs

  admin:
    image: opencdx/admin:latest
    healthcheck:
      test: "curl --fail --silent localhost:8761/actuator/health | grep UP || exit 1"
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    ports:
      - "8761:8761"

  config:
    image: opencdx/config:latest
    volumes:
      - ../certs:/certs
    ports:
      - "8888:8888"
    depends_on:
      admin:
        condition: service_healthy
    healthcheck:
      test: "curl -k --fail --silent https://localhost:8888/actuator/health | grep UP || exit 1"
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  database:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
        - "27017:27017"
    healthcheck:
      test: "echo 'db.runCommand({serverStatus:1}).ok' | mongosh localhost:27017/test --quiet"
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  nats:
    image: nats
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    environment:
      NATS_STREAM_MAX_AGE: 86400s