# Properties for a Managed Environment go here.
spring:
  application:
    name: helloworld

opencdx:
  helloworld:
    format: "Hello %s!"

grpc:
  security:
    auth:
      enabled: true


logging:
  level:
    org:
      springframework:
        security: DEBUG