# Properties for a Managed Environment go here.
management:
  endpoint:
    health:
      probes:
        enabled: true
      enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    health:
      safe: debug

eureka:
  client:
    service-url:
      defaultZone: https://discovery:8761/eureka/
    tls:
      enabled: 'true'
      key-store: file:/certs/opencdx-keystore.p12
      key-store-type: PKCS12
      key-store-password: ${keystore.password}
      trust-store: file:/certs/opencdx-keystore.p12
      trust-store-type: PKCS12
      trust-store-password: ${truststore.password}
      key-password: opencdx
  instance:
    nonSecurePortEnabled: false
    securePortEnabled: true
    statusPageUrl: https://${spring.application.name}:${server.port}/info
    healthCheckUrl: https://${spring.application.name}:${server.port}/actuator/health
    homePageUrl: https://${spring.application.name}:${server.port}/

springdoc:
  api-docs:
    path: /api-docs

# Spring SSL bundle for securing a webserver
spring:
  ssl:
    bundle:
      jks:
        web-server:
          key:
            alias: ${spring.application.name}
          keystore:
            location: file:/certs/opencdx-keystore.p12
            password: ${keystore.password}
            keystore.type: PKCS12
  cache:
    type: generic
# Enable SSL for REST
server:
  port: 8080
  ssl:
    enabled: true
    bundle: web-server
    client-auth: none
  http2:
    enabled: true
# Enable SSL for gRPC
grpc:
  port: 9090
  security:
    cert-chain: file:/certs/${spring.application.name}-cert.pem
    private-key: file:/certs/${spring.application.name}-key.pem
    auth:
      enabled: true

keystore.password: '{cipher}AQADXNLA7chsQBDvpjwopq+NhAQ8JCgKJhnF2uQlGNRuCTm/N5cVuxoSFn2dkum8nSZHfXL5HfTZFF234Oz0LSZ9g2z4Qs4jQbNNCx2+JnzScSBjZknJfGujzXKiHFQRWDLdPPOoMyTrE20PLA9LIKxiVXhi3rOff5eEg6bvl43uHNEqgJEvB6ZKxVzBCfSkdEWM+/vBmfIX8MMh3PyqB4U/WrrIYTAYVPSxg5iekZrBfIYdgmIHlAmFx87mlOqmDpT62LZiWE1x9Kac2ojTtCA7BivZhkBtWTGseguPJYv+fJvi65+Mw23RGj5B5HsSPRB2h4cyLq+AleLzEwTFGoKoJgW1ltNgrytUei/OiFLnNZjaKWBjD/E3nUwztI09Q7k='
truststore.password: '{cipher}AQADXNLA7chsQBDvpjwopq+NhAQ8JCgKJhnF2uQlGNRuCTm/N5cVuxoSFn2dkum8nSZHfXL5HfTZFF234Oz0LSZ9g2z4Qs4jQbNNCx2+JnzScSBjZknJfGujzXKiHFQRWDLdPPOoMyTrE20PLA9LIKxiVXhi3rOff5eEg6bvl43uHNEqgJEvB6ZKxVzBCfSkdEWM+/vBmfIX8MMh3PyqB4U/WrrIYTAYVPSxg5iekZrBfIYdgmIHlAmFx87mlOqmDpT62LZiWE1x9Kac2ojTtCA7BivZhkBtWTGseguPJYv+fJvi65+Mw23RGj5B5HsSPRB2h4cyLq+AleLzEwTFGoKoJgW1ltNgrytUei/OiFLnNZjaKWBjD/E3nUwztI09Q7k='