# Properties for a Managed Environment go here.
spring:
  application:
    name: anf

opencdx:
  helloworld:
    format: "Hello %s!"

mongock:
  change-logs-scan-package: cdx.opencdx.anf.changelog
  max-waiting-for-lock-minutes: 5
  lock-acquired-for-minutes: 3