# Properties for a Managed Environment go here.
grpc:
  port: 9090

management:
  endpoint:
    health:
      enabled: true
logging:
  level:
    health:
      safe: debug
spring:
  application:
    name: Tinkar
  datasource:
    url: jdbc:h2:mem:opencdx
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

opencdx:
  helloworld:
    format: "Hello %s!"
  tinkar:
    format: "Hello %s!"