# Properties for a Managed Environment go here.
grpc:
  port: 9090

management:
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    health:
      safe: debug
spring:
  application:
    name: Tinkar
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driverClassName: ${SPRING_DATASOURCE_DRIVER}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    database-platform: ${SPRING_JPA_DATABASE_PLATFORM}
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
  boot:
    admin:
      client:
        url: http://admin:761/admin/
opencdx:
  helloworld:
    format: "Hello %s!"
  tinkar:
    format: "Hello %s!"

eureka:
  client:
    service-url:
      defaultZone: http://admin:8761/eureka/



