# Properties for a Managed Environment go here.
spring:
  application:
    name: classification

opencdx:
  client:
    media:
      enabled: true
    connected-test:
      enabled: true
    questionnaire:
      enabled: true