# Properties for a Managed Environment go here.
spring:
  application:
    name: classification

opencdx:
  client:
    media:
      enabled: true
    health:
      enabled: true
    questionnaire:
      enabled: true
    logistics:
      enabled: true
  engines:
    default: classificationEngineDefault

mongock:
  change-logs-scan-package: cdx.opencdx.classification.changelog
  max-waiting-for-lock-minutes: 3
  lock-acquired-for-minutes: 2
  max-tries: 5
  service-identifier: ${spring.application.name}