# Properties for a Managed Environment go here.
spring:
  application:
    name: audit

mongock:
  change-logs-scan-package: cdx.opencdx.audit.changelog
  max-waiting-for-lock-minutes: 5
  lock-acquired-for-minutes: 3