# Properties for a Managed Environment go here.
spring:
  application:
    name: Config
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config/{profile}

server:
  port: 8888
  ssl:
    enabled: true
    client-auth: none
    key-store: file:/certs/opencdx-keystore.p12
    key-store-password: opencdx
    key-alias: ${spring.application.name}