# Properties for a Managed Environment go here.
spring:
  application:
    name: Config
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config/{profile}

server:
  port: 8888


