# Properties for a Managed Environment go here.
spring:
  application:
    name: Config

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config/{profile}
      tls:
        key-store: file:/certs/opencdx-keystore.p12
        trust-store-type: PKCS12
        key-store-type: PKCS12
        key-password: opencdx
        trust-store: file:/certs/opencdx-keystore.p12
        trust-store-password: opencdx
        enabled: 'true'
        key-store-password: opencdx

server:
  port: 8888
  ssl:
    enabled: true
    client-auth: none
    key-store: file:/certs/opencdx-keystore.p12
    key-store-password: opencdx
    key-alias: ${spring.application.name}
  http2:
    enabled: true
management:
  endpoint:
    health:
      probes:
        enabled: true
      enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    service-url:
      defaultZone: https://discovery:8761/eureka/
    tls:
      enabled: 'true'
      key-store: file:/certs/opencdx-keystore.p12
      key-store-type: PKCS12
      key-store-password: opencdx
      trust-store: file:/certs/opencdx-keystore.p12
      trust-store-type: PKCS12
      trust-store-password: opencdx
      key-password: opencdx
  instance:
    nonSecurePortEnabled: false
    securePortEnabled: true
    statusPageUrl: https://${spring.application.name}:${server.port}/info
    healthCheckUrl: https://${spring.application.name}:${server.port}/actuator/health
    homePageUrl: https://${spring.application.name}:${server.port}/
encrypt:
  keyStore:
    location: file:/certs/config-server.jks
    alias: config-server-key
    password: opencdx