spring:
  application:
    name: Admin
  boot:
    admin:
      context-path: /admin

server:
  port: 8761

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF

management:
  endpoint:
    health:
      probes:
        enabled: true
      enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
