spring:
  application:
    name: Admin
  boot:
    admin:
      context-path: /admin
      ui:
        title: OpenCDX Admin
        brand: <span>OpenCDX Admin</span>
        external-views:
          - label: "Discovery"
            url: "https://localhost:8761/"
          - label: "NATS"
            url: "http://localhost:8222/"
          - label: "Zipkin"
            url: "http://localhost:9411/zipkin"
          - label: "Swagger"
            children:
              - label: "Anf"
                url: "https://localhost:8080/anf/swagger-ui/index.html"
              - label: "Audit"
                url: "https://localhost:8080/audit/swagger-ui/index.html"
              - label: "Classification"
                url: "https://localhost:8080/classification/swagger-ui/index.html"
              - label: "Communications"
                url: "https://localhost:8080/communications/swagger-ui/index.html"
              - label: "Connected Test"
                url: "https://localhost:8080/connected-test/swagger-ui/index.html"
              - label: "IAM"
                url: "https://localhost:8080/iam/swagger-ui/index.html"
              - label: "Media"
                url: "https://localhost:8080/media/swagger-ui/index.html"
              - label: "Predictor"
                url: "https://localhost:8080/predictor/swagger-ui/index.html"
              - label: "Protector"
                url: "https://localhost:8080/protector/swagger-ui/index.html"
              - label: "Questionnaire"
                url: "https://localhost:8080/questionnaire/swagger-ui/index.html"
              - label: "Routine"
                url: "https://localhost:8080/routine/swagger-ui/index.html"
              - label: "Tinkar"
                url: "https://localhost:8080/tinkar/swagger-ui/index.html"



server:
  port: 8861
  ssl:
    enabled: true
    client-auth: none
    key-store: file:/certs/opencdx-keystore.p12
    key-store-password: opencdx
    key-alias: admin

management:
  endpoint:
    health:
      probes:
        enabled: true
      enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    enabled: true
    sampling.probability: 1.0
    propagation:
      type: b3
logging.pattern.level: "trace_id=%mdc{traceId} span_id=%mdc{spanId} trace_flags=%mdc{traceFlags} %p"


eureka:
  client:
    service-url:
      defaultZone: https://discovery:8761/eureka/
    tls:
      enabled: 'true'
      key-store: file:/certs/opencdx-keystore.p12
      key-store-type: PKCS12
      key-store-password: opencdx
      trust-store: file:/certs/opencdx-keystore.p12
      trust-store-type: PKCS12
      trust-store-password: opencdx
      key-password: opencdx
  instance:
    nonSecurePortEnabled: false
    securePortEnabled: true
    statusPageUrl: https://${spring.application.name}:${server.port}/info
    healthCheckUrl: https://${spring.application.name}:${server.port}/actuator/health
    homePageUrl: https://${spring.application.name}:${server.port}/