spring:
  datasource:
    url: jdbc:postgresql://database:5432/opencdx
    driverClassName: mongodb.jdbc.MongoDriver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create