# Properties for a Managed Environment go here.
grpc:
  port: 9090

management:
  endpoint:
    health:
      probes:
        enabled: true
      enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    health:
      safe: debug

spring:
  boot:
    admin:
      client:
        url: http://admin:761/admin/

eureka:
  client:
    service-url:
      defaultZone: http://admin:8761/eureka/

server:
  port: 8081