# Properties for a Managed Environment go here.
management:
  endpoint:
    health:
      probes:
        enabled: true
      enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    health:
      safe: debug

eureka:
  client:
    service-url:
      defaultZone: http://admin:8761/eureka/

springdoc:
  api-docs:
    path: /api-docs